#!/bin/bash

LOG=${LOG:-$1}
date
cat $LOG | awk -v file=$LOG '
/Local/{	
	num++
	data += $8
	time += $10

	if (data_min > $8)
		data_min = $8
	if (data_max < $8)
		data_max = $8

	if (time_min > $10)
		time_min = $10
	if (time_max < $10)
		time_max = $10

	data_file = file ".data"
	time_file = file ".time"

	print $8 >> data_file
	print $10 >> time_file
}

END {
	close(data_file)
	close(time_file)

	printf "SUMMARY\n"
	printf "-----------------------------------\n"
	printf "%-16s %d\n", "Connection", num
	printf "%-16s %d B\n", "Data min", data_min
	printf "%-16s %.1f B\n", "Data avg", data/num
	printf "%-16s %d B\n", "Data max", data_max
	printf "%-16s %d ms\n", "Time min", time_min
	printf "%-16s %.1f ms\n", "Time avg", time/num
	printf "%-16s %d ms\n", "Time max", time_max
	printf "\n"
}
'

ARRAY=("data" "time")
for name in ${ARRAY[@]}
do
	FILE=$LOG.$name
	sort -n $FILE -o $FILE
	NUM=`wc -l $FILE | awk '{print $1}'`

	printf "%s PERCENTILE\n" `echo $name|tr '[a-z]' '[A-Z]'`
	printf "%s\n" "-----------------------------------"
	cat $FILE | awk -v num=$NUM '
		BEGIN {
			perc[0] = int(0.01 * num)
			for (i = 1; i < 10; i++)
				perc[i] = int(i * num / 10)
			perc[10] = int(0.99 * num)
		}

		{
			for (i = 0; i <= 10; i++)
				if (NR == perc[i]) {
					str = 10 * i
					if (str == 0)
						str = 1
					else if (str == 100)
						str = 99

					printf "%-16s %d\n", str"""th", $1
				}
		}

		END {
			printf "\n"
		}
	'
	rm -f $FILE
done

date
